import { useEffect, useState } from 'react'
import { Download, FileText, HardDrive, MoreVertical, Plus, RefreshCw, Search, Trash2, Upload, UserCheck, UserX, Users, Activity, Database, ShieldCheck } from 'lucide-react'
import api, { getErrorMessage } from './api'
import { EmptyState, PageHeader, StatCard, Toast, UploadDropzone } from './components'
import { formatBytes, formatDate } from './utils'
import { useAuth } from './context/AuthContext'

function useToast() { const [toast, setToast] = useState(null); return { toast, notify: (message, type = 'success') => setToast({ message, type }), clear: () => setToast(null) } }

function getGreeting() {
  const hour = new Date().getHours()
  if (hour < 12) return 'Good morning'
  if (hour < 17) return 'Good afternoon'
  return 'Good evening'
}

export function Dashboard() {
  const { user } = useAuth(); const [stats, setStats] = useState(null); const [recent, setRecent] = useState([]); const { toast, notify, clear } = useToast()
  useEffect(() => { Promise.all([api.get('/api/dashboard/stats'), api.get('/api/files/personal')]).then(([statsResponse, filesResponse]) => { setStats(statsResponse.data); setRecent(filesResponse.data.files.slice(0, 5)) }).catch((error) => notify(getErrorMessage(error), 'error')) }, [])
  return <><PageHeader eyebrow="Overview" title={`${getGreeting()}, ${user?.username}.`} description="Here’s what’s happening in your workspace today." action={<a className="button button-primary" href="/upload"><Upload size={17} />Upload files</a>} />
    <div className="stats-grid"><StatCard label="Personal files" value={stats?.file_count ?? '—'} caption="Files in your workspace" icon={FileText} accent="blue" /><StatCard label="Storage used" value={stats ? formatBytes(stats.storage_bytes) : '—'} caption="Across personal files" icon={HardDrive} accent="mint" /><StatCard label="Last upload" value={stats?.last_uploaded ? formatDate(stats.last_uploaded.uploaded_at).split(',')[0] : '—'} caption={stats?.last_uploaded?.original_name || 'No uploads yet'} icon={RefreshCw} accent="amber" /></div>
    <section className="panel"><div className="panel-heading"><div><h2>Recent personal files</h2><p>Your latest uploads, available wherever you work.</p></div><a className="text-link" href="/files/personal">View all <span>→</span></a></div>{recent.length ? <FileTable files={recent} onChanged={() => {}} compact /> : <EmptyState title="No files yet" text="Upload your first document to get started." action={<a className="button button-secondary" href="/upload"><Upload size={16} />Upload a file</a>} />}</section><Toast toast={toast} onClose={clear} /></>
}

function FileTable({ files, onChanged, compact = false, admin = false }) {
  const { user } = useAuth(); const { toast, notify, clear } = useToast()
  const download = async (file) => { try { const response = await api.get(`/api/files/download/${file.id}`, { responseType: 'blob' }); const url = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = file.original_name; link.click(); URL.revokeObjectURL(url) } catch (error) { notify(getErrorMessage(error), 'error') } }
  const remove = async (file) => { if (!window.confirm(`Delete ${file.original_name}?`)) return; try { await api.delete(`/api/files/${file.id}`); notify('File deleted'); onChanged() } catch (error) { notify(getErrorMessage(error), 'error') } }
  return <><div className="table-wrap"><table><thead><tr><th>Name</th>{admin && <th>Owner</th>}<th>Size</th><th>Uploaded</th><th aria-label="Actions" /></tr></thead><tbody>{files.map((file) => <tr key={file.id}><td><div className="file-name"><div className="file-type"><FileText size={17} /></div><span>{file.original_name}<small>{file.folder === 'common' ? 'Common file' : 'Personal file'}</small></span></div></td>{admin && <td>{file.username}</td>}<td>{formatBytes(file.size)}</td><td>{formatDate(file.uploaded_at)}</td><td><div className="row-actions"><button className="icon-button" title="Download" onClick={() => download(file)}><Download size={17} /></button>{(!admin || user?.role === 'admin' || file.user_id === user?.id) && <button className="icon-button danger-hover" title="Delete" onClick={() => remove(file)}><Trash2 size={17} /></button>}</div></td></tr>)}</tbody></table></div><Toast toast={toast} onClose={clear} /></>
}

export function FilesPage({ folder = 'personal' }) {
  const [files, setFiles] = useState([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const { toast, notify, clear } = useToast()
  const load = () => { setLoading(true); api.get(`/api/files/${folder}`, { params: search ? { search } : {} }).then(({ data }) => setFiles(data.files)).catch((error) => notify(getErrorMessage(error), 'error')).finally(() => setLoading(false)) }
  useEffect(load, [folder])
  return <><PageHeader eyebrow={folder === 'personal' ? 'My workspace' : 'Shared workspace'} title={folder === 'personal' ? 'My files' : 'Common files'} description={folder === 'personal' ? 'Documents only you can access.' : 'Files shared with everyone in the organization.'} action={<a className="button button-primary" href="/upload"><Upload size={17} />Upload files</a>} /><section className="panel"><div className="toolbar"><div className="search-box"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && load()} placeholder="Search files" /><button onClick={load}>Search</button></div><button className="button button-quiet" onClick={load}><RefreshCw size={16} />Refresh</button></div>{loading ? <div className="loading">Loading files…</div> : files.length ? <FileTable files={files} onChanged={load} /> : <EmptyState title="No files found" text={search ? 'Try a different search term.' : 'Upload a file to see it here.'} />}</section><Toast toast={toast} onClose={clear} /></>
}

export function UploadPage() {
  const [files, setFiles] = useState([]); const [folder, setFolder] = useState('personal'); const [uploading, setUploading] = useState(false); const [progress, setProgress] = useState(0); const { toast, notify, clear } = useToast()
  const submit = async (event) => { event.preventDefault(); if (!files.length) return notify('Choose at least one file first.', 'error'); const form = new FormData(); form.append('folder', folder); files.forEach((file) => form.append('files', file)); setUploading(true); setProgress(0); try { await api.post('/api/files/upload', form, { onUploadProgress: (event) => setProgress(event.total ? Math.round((event.loaded * 100) / event.total) : 0) }); notify(`${files.length} file${files.length > 1 ? 's' : ''} uploaded successfully.`); setFiles([]); setProgress(100) } catch (error) { notify(getErrorMessage(error), 'error') } finally { setUploading(false) } }
  return <><PageHeader eyebrow="File center" title="Upload files" description="Securely add documents to your personal or shared workspace." /><div className="upload-layout"><form className="panel upload-panel" onSubmit={submit}><UploadDropzone files={files} setFiles={setFiles} uploading={uploading} />{uploading && <div className="progress-block"><div><span>Uploading files</span><strong>{progress}%</strong></div><div className="progress-bar"><span style={{ width: `${progress}%` }} /></div></div>}<div className="form-footer"><label className="field"><span>Upload destination</span><select value={folder} onChange={(event) => setFolder(event.target.value)} disabled={uploading}><option value="personal">My personal files</option><option value="common">Common files</option></select></label><button className="button button-primary" disabled={uploading || !files.length}><Upload size={17} />{uploading ? 'Uploading…' : 'Start upload'}</button></div></form><aside className="panel upload-help"><h3>Before you upload</h3><p>Keep your workspace organized with a few simple guidelines.</p><ul><li><ShieldCheck size={17} /><span>Files are protected by your secure session.</span></li><li><FileText size={17} /><span>Executable file types are blocked automatically.</span></li><li><Database size={17} /><span>Individual files can be up to 500 MB.</span></li></ul></aside></div><Toast toast={toast} onClose={clear} /></>
}

export function AdminPage() {
  const [tab, setTab] = useState('overview'); const [stats, setStats] = useState(null); const [users, setUsers] = useState([]); const [files, setFiles] = useState([]); const [logs, setLogs] = useState([]); const [search, setSearch] = useState(''); const { toast, notify, clear } = useToast()
  const load = () => { const requests = [api.get('/api/admin/stats'), api.get('/api/admin/users'), api.get('/api/admin/files', { params: search ? { search } : {} }), api.get('/api/admin/logs')]; Promise.all(requests).then(([a, b, c, d]) => { setStats(a.data); setUsers(b.data.users); setFiles(c.data.files); setLogs(d.data.logs) }).catch((error) => notify(getErrorMessage(error), 'error')) }
  useEffect(load, [])
  const updateUser = async (user) => { try { await api.put(`/api/admin/users/${user.id}`, { is_active: !user.is_active }); notify(`${user.username} is now ${user.is_active ? 'inactive' : 'active'}.`); load() } catch (error) { notify(getErrorMessage(error), 'error') } }
  const deleteUser = async (user) => { if (!window.confirm(`Delete user ${user.username}?`)) return; try { await api.delete(`/api/admin/users/${user.id}`); notify('User deleted'); load() } catch (error) { notify(getErrorMessage(error), 'error') } }
  const tabs = [['overview', 'Overview'], ['users', 'Users'], ['files', 'All files'], ['logs', 'Activity logs']]
  return <><PageHeader eyebrow="Administration" title="Control center" description="Manage users, files, and portal activity." action={<button className="button button-quiet" onClick={load}><RefreshCw size={16} />Refresh</button>} /><div className="tabs">{tabs.map(([key, label]) => <button className={tab === key ? 'active' : ''} key={key} onClick={() => setTab(key)}>{label}</button>)}</div>{tab === 'overview' && <div className="stats-grid admin-stats"><StatCard label="Total users" value={stats?.total_users ?? '—'} caption={`${stats?.active_users ?? '—'} active accounts`} icon={Users} accent="blue" /><StatCard label="Total files" value={stats?.total_files ?? '—'} caption={formatBytes(stats?.storage_bytes)} icon={FileText} accent="mint" /><StatCard label="Today's logins" value={stats?.today_logins ?? '—'} caption={`${stats?.failed_logins ?? '—'} failed attempts overall`} icon={Activity} accent="amber" /></div>}{tab === 'users' && <AdminUsers users={users} updateUser={updateUser} deleteUser={deleteUser} notify={notify} reload={load} />}{tab === 'files' && <section className="panel"><AdminToolbar search={search} setSearch={setSearch} onSearch={load} /><FileTable files={files} onChanged={load} admin /></section>}{tab === 'logs' && <section className="panel"><div className="panel-heading"><div><h2>Activity logs</h2><p>Recent security and workspace events.</p></div></div><div className="table-wrap"><table><thead><tr><th>Event</th><th>User</th><th>Details</th><th>Status</th><th>Time</th></tr></thead><tbody>{logs.map((log) => <tr key={log.id}><td><strong>{log.action.replaceAll('_', ' ')}</strong></td><td>{log.username || 'System'}</td><td>{log.detail}</td><td><span className={`status ${log.status}`}>{log.status}</span></td><td>{formatDate(log.created_at)}</td></tr>)}</tbody></table></div></section>}<Toast toast={toast} onClose={clear} /></>
}

function AdminToolbar({ search, setSearch, onSearch }) { return <div className="toolbar"><div className="search-box"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && onSearch()} placeholder="Search files" /><button onClick={onSearch}>Search</button></div></div> }
function AdminUsers({ users, updateUser, deleteUser, notify, reload }) {
  const [form, setForm] = useState({ username: '', password: '', role: 'employee' }); const [show, setShow] = useState(false)
  const create = async (event) => { event.preventDefault(); try { await api.post('/api/admin/users', form); notify('User created'); setForm({ username: '', password: '', role: 'employee' }); setShow(false); reload() } catch (error) { notify(getErrorMessage(error), 'error') } }
  return <section className="panel"><div className="panel-heading"><div><h2>User directory</h2><p>Activate, deactivate, and manage portal accounts.</p></div><button className="button button-primary" onClick={() => setShow(!show)}><Plus size={17} />Add user</button></div>{show && <form className="inline-form" onSubmit={create}><input required placeholder="Username" value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} /><input required minLength="8" type="password" placeholder="Temporary password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /><select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}><option value="employee">Employee</option><option value="admin">Admin</option></select><button className="button button-primary">Create</button></form>}<div className="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Created</th><th /></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td><div className="user-cell"><div className="avatar small">{user.username.slice(0, 2).toUpperCase()}</div><strong>{user.username}</strong></div></td><td><span className="role-tag">{user.role}</span></td><td><span className={`status ${user.is_active ? 'success' : 'failed'}`}>{user.is_active ? 'Active' : 'Inactive'}</span></td><td>{formatDate(user.created_at)}</td><td><div className="row-actions"><button className="icon-button" title={user.is_active ? 'Deactivate' : 'Activate'} onClick={() => updateUser(user)}>{user.is_active ? <UserX size={17} /> : <UserCheck size={17} />}</button>{user.role !== 'admin' && <button className="icon-button danger-hover" title="Delete" onClick={() => deleteUser(user)}><Trash2 size={17} /></button>}</div></td></tr>)}</tbody></table></div></section>
}
